### PR TITLE
Convert Promises code of Launcher PR command into async/await

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
Hopefully this improves the readability of the code

**Comment by metacosm** [comment]
Much more readable to me at least. Thanks! 💯

**Comment by geoand** [comment]
Now that it great to hear!!! @gytis WDYT?

**Comment by gytis** [comment]
Yep nice work! I'm kind of used to promises, but await is surely easier to understand.

**Comment by geoand** [comment]
Glad to hear! I'll take up refactoring the rest in due time

**Pull request merged**
