### PR TITLE
Jira management class and clone issue command

### PR DESCRIPTION
**Pull request by gytis**
This is a simplified cloning operation because there is no API for the actual cloning of the jira issues. It can clone an issue with its subtasks recursively but only a limited number of fields will be taken.

This clone command takes the original summary as is. For the prod issue cloning we need to modify the summary. So what would be your preference: to have an option to override summary during cloning or having a dedicate summary update command? Second option would be my preference.

In addition, if the "create jira issue" command is not used, I propose to remove it. Otherwise I would have to refactor it to reuse the new Jira class.

### CODE REVIEW

**Comment by geoand** [comment]
The test failure is unrelated to the PR, I'm looking into it

**Comment by geoand** [comment]
@gytis Can you please rebase onto the latest master in order to pick up the test fixes?

PR looks great to me! I am good with what you propose. @metacosm WDYT?

**Comment by gytis** [comment]
Seems that lint checks were changed, I'll fix them and update

**Comment by gytis** [comment]
Or maybe they weren't changed but only weren't executed because of failing tests. In any case I ran link:fix and it sorted things out at least locally.

**Comment by geoand** [comment]
LGTM!

**Pull request merged**
