### PR TITLE
Upgrade licenses generator to 1.0.2

### PR DESCRIPTION
**Pull request by gytis**

### CODE REVIEW

**Comment by geoand** [comment]
I suppose this has to do with the licenses urls issue?

**Comment by gytis** [comment]
Yep, I've added a new URL entry

**Comment by gytis** [comment]
I'll create a JIRA to improve the generator to accept external config, so that we could store it somewhere else and not require a release on every change

**Comment by geoand** [comment]
Cool!

**Comment by geoand** [comment]
Seems like the test failed. Can you please take a look @gytis ?

**Comment by gytis** [comment]
Damn, I merged them anyway because I thought that CI is still failing because of incompatibility

**Comment by gytis** [comment]
Let me check the logs

**Comment by gytis** [comment]
There seems to be a problem with it, I'll revert

**Comment by geoand** [comment]
No worries :)

**Comment by gytis** [comment]
Crap, I missed a comma in the json, need to make another release. I won't rever but just update a jar

**Comment by geoand** [comment]
:+1:

**Pull request merged**
