### PR TITLE
#37 Update to use new catalog.json format

### PR DESCRIPTION
**Pull request by gytis**
I rewrote the whole script inline with the current launcher catalogue format. I didn't have a chance to test it with an actual catalogue because it's currently up to date. Based on the tests it works, but you never know before trying it in real life.

Please, take a look and let me know what you think. We could merge it and try it together during the next release.

### CODE REVIEW

**Comment by geoand** [comment]
CI doesn't seem to agree :(

**Comment by gytis** [comment]
ah right, forgot to run lint :/

**Comment by gytis** [comment]
CI fixed

**Comment by gytis** [comment]
I'm merging it it and will revisit it once we have a release to take are of.

**Pull request merged**
