### PR TITLE
Create JIRA issue

### PR DESCRIPTION
**Pull request by gytis**
https://issues.jboss.org/browse/SB-969

### CODE REVIEW

**Comment by geoand** [comment]
@gytis Have you tested it against our JIRA?

**Comment by gytis** [comment]
Yes all good. But it's only the slack command, not integrated into the release process

**Comment by geoand** [comment]
Also, Gytis can you run the linting process to get CI working?

**Comment by gytis** [comment]
should be good now

**Comment by geoand** [comment]
:+1:

**Pull request merged**
